### ISSUE TITLE
Remove comments from the output

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-cli-node-avocado#13]
We need to add a new file (Step) in the `helpers` folder after step `04_render.js` and call it `05_diet` where we will have a chain of promises that removes all the comments for the `_output` folder. Each language needs to have its own promise even if it will have just one line of code.

- CSS comments
- HTML comments
- JS comments

**Comment by davidgatti** [comment]
Work on this after you finish this #23

**Comment by Jarmahent** [comment]
@davidgatti Ok I have the a regex solution that I can start testing, just give me some more info on how to start the `06_diet.js` file off and I can do the rest.

**Comment by davidgatti** [comment]
If you take a look at the other files you'll see that they have a lot of similarities, you just need to copy the content of one file, and remove what is unnecessary, and add the promises that needs to be added to fulfill the Issue description.

Based on this do it, in a way that you think make sense, and if you are off, I can put you back on track.

**Comment by Jarmahent** [comment]
Sounds good!
