### ISSUE TITLE
Add support for custom formatting in the .eslintrc.json file

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-cli-node-avocado#19]
In the root directory this repo there is this .eslintrc.json file, which is a configuration file for https://eslint.org/. I almost have the whole configuration in place, the thing that is missing is the following scenario.

```
do_something(function() {

	// new line above, new line bellow

})
```

In a scenario of a anonymous function, we want to visually separate the code

```
if()
{
	// no new line above or bellow
}
```
In this situation the braces already visually splits the code, so no need for new lines.

I think this could be achieved with this https://eslint.org/docs/rules/padding-line-between-statements rule, but I'm not sure. Please check it out, and see if it is possible to achieve this, you can also ask for help here https://github.com/eslint/eslint, or any other place.

**Comment by Jarmahent** [comment]
So you want eslint to change anything that doesn't follow this rule when you add `--fix`?

**Comment by Jarmahent** [comment]
Eslint works for throwing errors for the second scenario but the for the first one it does not I will work on that.

**Comment by Jarmahent** [comment]
I found a [padded-blocks](https://eslint.org/docs/rules/padded-blocks) rule but it doesnt not work because it triggers it for everything that is a block.

I have also tried using padding-in-between-statement rules to narrow it down to functions but for some reason it is not working heres what I am doing:
```js
"padding-line-between-statements": [
          "error",
          { "blankLine": "always", "prev": "function", "next": "*"
        }]
```

Basically what the rule should do is make it so a blank line must be present after a function and anything that come after the blank line. But for some weird reason it is not triggering with example:


```
doHomework('math', function() {
	const kevin = "Kevin";
});
```
Ill keep trying to fix it though.

**Comment by davidgatti** [comment]
Good work, and once you get an idea of what is going on, don't hesitate to ask the internet for some suggestions.

**Comment by Jarmahent** [comment]
@davidgatti  I have been asking around for a while and I have come to the conclusion that eslint does not have the ability to specifically padding for only function blocks.

 Like I said before `padded-blocks` triggers the rule for everything. You can Add a `Block`, `Classes`, or `Switch` case for `padded-blocks` but there is no option for functions only. 

It looks like for now there is not possible way to specifically add padding for functions.

**Comment by davidgatti** [comment]
Hmm ok, I see good work doing the research :)
