### ISSUE TITLE
Custom comment formatting in ESLint

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-cli-node-avocado#20]
Similar to Issue #19 I want to find out is it possible to have a check for this style of comment:

```
//
//    1. Hello
//
```

ESLint has a rule to add a space before and after a comment, but I want this space to be `//`, and the problem is that `//` is a comment, so you see the issue :) 

See if there is a way to have this, and let me know off the finding.

**Comment by Jarmahent** [comment]
Working on this rule now!

**Comment by davidgatti** [comment]
Move issue to new repo under this issue 0x4447/eslint-plugin-0x4447#2
