### ISSUE TITLE
New feature: Test version

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-cli-node-avocado#36]
# My Problem

Right now we just have a dummy test, but I want to have one that actually dose something.

# Solution

I'd like for the test to run `avocado -V`, to pull the version and compare it with what is in the package.json file. This simple action will test if the app actually works.

**Comment by Jarmahent** [comment]
So this test will check the version of the currently installed Avacado to the NPM version?

**Comment by davidgatti** [comment]
Yes.

**Comment by Jarmahent** [comment]
So for example if I run:

`avocado -V` and I have an outdated version of Avocado it will say:

`There is a new version of Avocado available just do npm update @0x4447/avocado`

**Comment by davidgatti** [comment]
No, the test will install avocado, by using pack, once this is done, you do `avocado -V`, grab the output, clean it, et to jsut get the version, then load the `package.json` file, get the version number and compare the two. 

If this action was successful it means the app works. I mean it at least starts.

This test will be normally performed in a CI (Continuous Integration) type server.
